### PR TITLE
Fix high CPU on retries in json_batch mode

### LINKED ISSUE #86: HTTP output causes Logstash to consume all CPU on DNS resolution failure
I've noticed on multiple occasions, that when the HTTP output is configured, but say the hostname is set incorrectly or the network is even down, that Logstash will use all CPU due to a name resolution failure.

- Version: 6.2.4-6.3.0
- Operating System: Linux
- Config File:
```
output {
  http {
    url => 'https://web.service.net/events'
    http_method => 'post'
    format => 'json_batch'
    headers => ['Authorization', 'XXXXXXXXX']
  }
}
```
- Steps to Reproduce: configure hostname incorrectly, unplug network, or block DNS

### PR DESCRIPTION
**Pull request by danhermann**
The high CPU on retries occurred because there was a separate code path for `json_batch` mode where retries were attempted in a hot loop. This PR unifies those code paths so that the proper back-off behavior is applied to retries in all modes.

Fixes #86, #88.

### CODE REVIEW

File: lib/logstash/outputs/http.rb [hunk 1]
```diff
@@ -182,16 +156,21 @@ def send_events(events)
     successes = java.util.concurrent.atomic.AtomicInteger.new(0)
     failures  = java.util.concurrent.atomic.AtomicInteger.new(0)
     retries = java.util.concurrent.atomic.AtomicInteger.new(0)
-    
+    event_count = @format == "json_batch" ? 1 : events.size
+
     pending = Queue.new
-    events.each {|e| pending << [e, 0]}
+    if @format == "json_batch"
+      pending << [events, 0, true]
```
Comment (jsvd) [inline lib/logstash/outputs/http.rb]: By setting a `@is_batch` variable (w/ a `is_batch` accessor) to true or false based on the `:format` parameter during the `register` method we can avoid passing it around in multiple places, greatly simplifying the code. wdyt?

File: lib/logstash/outputs/http.rb [hunk 2]
```diff
@@ -246,11 +227,11 @@ def send_event(event, attempt)
...
 
     # Send the request
-    url = event.sprintf(@url)
-    headers = event_headers(event)
+    url = @is_batch ? @url : event.sprintf(@url)
+    headers = @is_batch ? @headers : event_headers(event)
 
     # Compress the body and add appropriate header
-    if @http_compression == true
+    if @http_compression == true && !@is_batch
```
Comment (jsvd) [inline lib/logstash/outputs/http.rb]: I know this is to keep current behaviour but the [current behaviour is a bug](https://github.com/logstash-plugins/logstash-output-http/issues/87) so we can fix it here too, also replacing  https://github.com/logstash-plugins/logstash-output-http/pull/88

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,3 +1,6 @@
+## 5.2.2
+  - Fix high CPU usage on retries in json_batch mode.
```
Comment (jsvd) [inline CHANGELOG.md]: sorry, one last detail, can you add the this pr's reference to the changelog entry? we have guidelines for editing the changelog [here](https://github.com/elastic/logstash/blob/master/CONTRIBUTING.md#logstash-plugin-changelog-guidelines) (these guidelines are somewhat recent we need to make them easier to find).
